### PR TITLE
fix prints for py3

### PR DESCRIPTION
**Pull request by Borda**
Particular fix to be able to run also python 3.x as py2 is not supported anymore...

### CODE REVIEW

**Comment by Borda** [comment]
@jcoffland @informatorius @PeterDaveHello ^^

**Comment by jcoffland** [comment]
This all looks good.  Thank you for doing this.

**Comment by Borda** [comment]
I guess that this could be useful https://github.com/FoldingAtHome/fah-control/issues/39
Will you do it or shall I try it and send another PR?

**Comment by jcoffland** [comment]
As long as autoconverting does not make a huge mess out of the code.  By all means send a PR.

**Comment by Borda** [comment]
sure, do you have some tests to check that it doesn't break anything?

**Comment by jcoffland** [comment]
Nothing automated.  I will review the changes.

**Pull request merged**
